### ISSUE TITLE
How can I view the animation?

### ISSUE THREAD

**Issue by TaimaniNTR** [myssal/Brown-Dust-2-Asset#6]
Hi, I'm new to this so excuse me, but I tried to use spine, and it either tells me to use V 4.1.11 or the pro version.

so how can i view the full animation from ( .atlas  .png  .skel ) without using spine?

i just want to use the clean animation as a background, nothing more xD

edit: ok I'm tired at this point, i tried every skeletonViewer version possible + like 8 different ways of skel2json to read these files and view the animation... i guess java , python or unity is not for me :(

**Comment by myssal** [comment]
[Skeleton Viewer](https://en.esotericsoftware.com/spine-skeleton-viewer) or Unity with [Spine Runtime 4.1](https://en.esotericsoftware.com/files/runtimes/unity/spine-unity-4.1-2024-06-19.unitypackage).

**Comment by TaimaniNTR** [comment]
tyvm,  i had to delete everything and do a fresh stand alone jdk and run " java -jar skeletonViewer-4.1.24.jar "  this was the only working one for me xD
